const UPDATE_PEOPLE = "UPDATE_PEOPLE";
const UPDATE_PAGINATION = "UPDATE_PAGINATION";
const UPDATE_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";

export {UPDATE_PEOPLE, UPDATE_PAGINATION, UPDATE_CURRENT_PAGE}